# # Use an official Node.js runtime as a parent image
# FROM node:18

# # Set the working directory in the container
# WORKDIR /usr/src/app

# # Copy package.json and package-lock.json to the working directory
# COPY package*.json ./

# # Install Angular CLI globally and project dependencies
# RUN npm install -g @angular/cli@latest && npm install

# # Copy the current directory contents into the container at /usr/src/app
# COPY . .

# # Expose the port the app runs on
# EXPOSE 4200

# # Command to run the Angular application
# CMD ["ng", "serve", "--host", "0.0.0.0"]

# Use an official Node.js image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 4200

# Run the Angular app
CMD ["npm", "start"]

