# This workflow will push built Angular code in dist folder to the remote server
#
# Steps to set up before workflow works.
#
# 1. Create `VPS_SSH_PASSWORD_HOSTINGER`, `USER_IP_HOSTINGER`, and 'IP_HOSTINGER' secrets in repository settings.
#      The first is the SSH password, the second is 'user@ip_address', and the last is just the ip.
#
#    See the documentation for each action used below

name: Deploy Frontend to VPS Server

on:
  push:
    branches: [ "main" ]

# env:
  # VPS_SSH_PASSWORD: VPS_SSH_PASSWORD_HOSTINGER     # set this to the password for the vps
  # USER_IP: USER_IP_HOSTINGER                       # set this to the user plus ip address of server

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup SSH
      id: ssh-setup
      env:
        USER_IP: ${{ secrets.USER_IP_HOSTINGER }}
        IP: ${{ secrets.IP_HOSTINGER }}
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIV_KEY_HOSTINGER }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUB_KEY_HOSTINGER }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan -H ${{ secrets.IP_HOSTINGER }} >> ~/.ssh/known_hosts

    - name: Deploy Frontend
      run: |
        rsync -vrm  frontend/dist/frontend/* ${{ secrets.USER_IP_HOSTINGER }}:/usr/local/lsws/Example/html/teachSubDomain/teachGenie/frontend/
